services:
  - type: web
    name: flask-backend
    env: python
    buildCommand: pipenv install
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
    region: oregon 



    

  - type: web
    name: react-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: build
    region: oregon 
